spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?autoReconnect=true&useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: 11133239
    driver-class-name: com.mysql.cj.jdbc.Driver